spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service
    username: postgres
    password: heyNulleviyDataBasePass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/database-changelog.yaml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

kafka:
  bootstrap-servers: localhost:9092
  topic:


server:
  port: 7331